# Generated by Django 4.2.4 on 2023-09-05 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_is_staff_customuser_is_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='is_admin',
            new_name='is_staff',
        ),
    ]
