# Generated by Django 4.2.4 on 2023-12-06 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_rename_is_admin_customuser_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
